language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

script:
 - /vendor/bin/phpunit

before_script:
 - composer selfupdate --quiet
 - composer install --no-interaction --prefer-source --dev

notifications:
  email:
    - me@mikevanriel.com
